name = "mumaa-api"
main = "src/index.ts"
compatibility_date = "2024-05-10"

[vars]
GOOGLE_CLIENT_ID = "776390108864-k41d9jj0snan12qmco02gl0mjkue286s.apps.googleusercontent.com"

[[d1_databases]]
binding = "DB"
database_name = "mumaa"
database_id = "e1f81027-1123-469e-8a8e-bcfd70ae9db1"
